import { useAuth } from "@/_core/hooks/useAuth";
import { CreatorSupportPanel } from "@/components/CreatorSupportPanel";
import { GuidedPackBuilder } from "@/components/GuidedPackBuilder";
import { MemphisShapes, SkootlyHeader } from "@/components/SkootlyHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { Check, CopyPlus, Lightbulb, Loader2, Plus, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";

const blankPack = { name: "", description: "" };
const labelFor = (kind: string) => kind.replaceAll("_", " ");
const date = (value?: number) => value ? new Date(value).toLocaleDateString() : "—";

export default function CreatorPacks() {
  const { user, loading } = useAuth();
  const utils = trpc.useUtils();
  const packsQuery = trpc.creatorPacks.list.useQuery(undefined, { enabled: Boolean(user) });
  const insights = trpc.creatorPacks.insights.useQuery(undefined, { enabled: Boolean(user) });
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const [newOpen, setNewOpen] = useState(false);
  const [guidedOpen, setGuidedOpen] = useState(false);
  const [packForm, setPackForm] = useState(blankPack);
  const [teaching, setTeaching] = useState("");
  const [editingProposalId, setEditingProposalId] = useState<number | null>(null);
  const [editingProposalContent, setEditingProposalContent] = useState("");
  const packs = packsQuery.data ?? [];
  const selected = useMemo(() => packs.find(pack => pack.id === selectedId) ?? null, [packs, selectedId]);
  const proposals = trpc.creatorPacks.listProposals.useQuery({ packId: selectedId ?? 0 }, { enabled: Boolean(selectedId) });
  useEffect(() => { if (!selectedId && packs[0]) setSelectedId(packs[0].id); }, [packs, selectedId]);
  const refresh = async () => { await utils.creatorPacks.list.invalidate(); await utils.creatorPacks.insights.invalidate(); if (selectedId) await utils.creatorPacks.listProposals.invalidate({ packId: selectedId }); };
  const create = trpc.creatorPacks.create.useMutation({ onSuccess: async result => { await refresh(); setSelectedId(result.packId); setPackForm(blankPack); setNewOpen(false); toast.success("Creator Pack created. Teach Skootly the first rule."); }, onError: error => toast.error(error.message) });
  const propose = trpc.creatorPacks.propose.useMutation({ onSuccess: async () => { await refresh(); setTeaching(""); toast.success("Knowledge proposal ready for review."); }, onError: error => toast.error(error.message) });
  const approve = trpc.creatorPacks.approve.useMutation({ onSuccess: refresh, onError: error => toast.error(error.message) });
  const cancel = trpc.creatorPacks.cancel.useMutation({ onSuccess: refresh, onError: error => toast.error(error.message) });
  if (loading || packsQuery.isLoading) return <div className="creator-loading"><Loader2 className="animate-spin" /> Loading Creator Packs…</div>;
  if (!user) return <div className="creator-loading">Sign in to create a Pack.</div>;

  return <div className="creator-page"><SkootlyHeader /><MemphisShapes quiet /><main className="creator-shell">
    <section className="creator-hero"><div><p className="eyebrow">CREATOR MODE</p><h1>Teach Skootly once.<br />Students get a clearer next move.</h1><p>Turn your evolving method into a short, reviewable execution path—not a giant prompt document.</p></div><Button onClick={() => setGuidedOpen(true)}><Plus className="size-4" /> Build a Skoot Pack</Button></section>
    <div className="creator-layout"><aside className="creator-pack-list"><div className="creator-list-heading"><span>Your Packs</span><Button size="icon" variant="outline" onClick={() => setGuidedOpen(true)} aria-label="Build a Skoot Pack"><Plus className="size-4" /></Button></div>{packs.length ? packs.map(pack => <button key={pack.id} onClick={() => setSelectedId(pack.id)} className={pack.id === selectedId ? "creator-pack-item creator-pack-item--active" : "creator-pack-item"}><b>{pack.name}</b><span>Version {pack.activeVersion?.versionNumber ?? 1} · {pack.assignments.length} student{pack.assignments.length === 1 ? "" : "s"}</span></button>) : <div className="creator-list-empty"><Lightbulb className="size-5" />Start with one Pack for one method.</div>}</aside>
      <section className="creator-workspace">{selected ? <><div className="creator-pack-heading"><div><p className="card-kicker">CURRENT PACK</p><h2>{selected.name}</h2><p>{selected.description || "Add a short description to clarify this method."}</p></div><div className="flex flex-wrap items-center gap-2"><Badge variant="outline">Version {selected.activeVersion?.versionNumber ?? 1} · updated {date(selected.updatedAt)}</Badge><Button size="sm" onClick={() => setGuidedOpen(true)}>Build / update path</Button></div></div>
        <article className="creator-teach-card"><div><p className="card-kicker">TEACH SKOOTLY</p><h3>What changed in your method?</h3><p>Say it naturally. Skootly makes a reviewable proposal; student guidance never changes silently.</p></div><Textarea value={teaching} onChange={event => setTeaching(event.target.value)} placeholder="I’ve learned that students should speak to 10 potential buyers before building their webinar." /><Button disabled={!teaching.trim() || propose.isPending} onClick={() => selectedId && propose.mutate({ packId: selectedId, sourceText: teaching })}>{propose.isPending ? <Loader2 className="size-4 animate-spin" /> : <CopyPlus className="size-4" />} Propose Pack update</Button></article>
        <section className="creator-proposals"><div className="section-heading"><div><p className="card-kicker">REVIEW BEFORE PUBLISHING</p><h3>Pending knowledge</h3></div><span>{proposals.data?.length ?? 0} pending</span></div>{proposals.data?.length ? proposals.data.map(item => <article className="creator-proposal" key={item.id}><div><Badge>{labelFor(item.proposedType)}</Badge><p className="proposal-source">“{item.sourceText}”</p>{editingProposalId === item.id ? <Textarea aria-label="Edit proposed Pack knowledge" value={editingProposalContent} onChange={event => setEditingProposalContent(event.target.value)} /> : <h4>{item.proposedContent}</h4>}</div><div className="proposal-actions">{editingProposalId === item.id ? <><Button size="sm" disabled={approve.isPending || !editingProposalContent.trim()} onClick={() => approve.mutate({ proposalId: item.id, content: editingProposalContent.trim() }, { onSuccess: () => { setEditingProposalId(null); setEditingProposalContent(""); } })}><Check className="size-3" /> Save & add</Button><Button size="sm" variant="outline" onClick={() => { setEditingProposalId(null); setEditingProposalContent(""); }}>Cancel edit</Button></> : <><Button size="sm" disabled={approve.isPending} onClick={() => approve.mutate({ proposalId: item.id })}><Check className="size-3" /> Add to Pack</Button><Button size="sm" variant="outline" onClick={() => { setEditingProposalId(item.id); setEditingProposalContent(item.proposedContent); }}>Edit</Button><Button size="sm" variant="outline" onClick={() => cancel.mutate({ proposalId: item.id })}><X className="size-3" /> Ignore</Button></>}</div></article>) : <div className="creator-empty-state">Your reviewable knowledge proposals will appear here.</div>}</section>
        <section className="creator-assign"><div><p className="card-kicker">ENROLL STUDENTS</p><h3>Create one private link per student.</h3><p>Open <b>Build / update path</b> above, then create an expiring invite after approving the Pack. Each student accepts their own link and stays pinned to that Pack version.</p></div>{selected.assignments.length ? <div className="student-chips">{selected.assignments.map(student => <span key={student.id}>{student.name || student.email || `Student #${student.studentUserId}`} <small>legacy assignment</small></span>)}</div> : null}</section>
        <CreatorSupportPanel />
      </> : <div className="creator-start"><Lightbulb className="size-8" /><h2>Create the first living Skoot Pack.</h2><p>Choose a short Pack shape, edit the path until it sounds like you, then approve it before anyone sees it.</p><Button onClick={() => setGuidedOpen(true)}>Build a Pack</Button></div>}</section>
      <aside className="creator-insights"><p className="card-kicker">EARLY SIGNALS</p><h2>What your students are experiencing</h2><div className="insight-number"><b>{insights.data?.assignedStudents ?? 0}</b><span>assigned student{(insights.data?.assignedStudents ?? 0) === 1 ? "" : "s"}</span></div><div className="insight-block"><h3>Getting stuck on</h3>{insights.data?.bottlenecks?.length ? insights.data.bottlenecks.map(item => <p key={item.label}>{item.label}<b>{item.count}</b></p>) : <p className="muted">Student check-ins will reveal patterns here.</p>}</div><div className="insight-block"><h3>Repeated questions</h3>{insights.data?.repeatedQuestions?.length ? insights.data.repeatedQuestions.map(item => <p key={item.label}>{item.label}<b>{item.count}</b></p>) : <p className="muted">Private conversations will contribute anonymous themes here.</p>}</div><div className="insight-block"><h3>Possible misconceptions</h3>{insights.data?.misconceptions?.length ? insights.data.misconceptions.map(item => <p key={item.label}>{item.label}<b>{item.count}</b></p>) : <p className="muted">Point A answers will surface anonymous belief patterns.</p>}</div><div className="insight-block"><h3>Frequently skipped</h3>{insights.data?.skippedSkoots?.length ? insights.data.skippedSkoots.map(item => <p key={item.label}>{item.label}<b>{item.count}</b></p>) : <p className="muted">Skipped Skoot patterns will appear here.</p>}</div><div className="insight-block"><h3>Stored outcomes</h3>{insights.data?.outcomeSummary?.length ? insights.data.outcomeSummary.map(item => <p key={item.label}>{labelFor(item.label)}<b>{item.count}</b></p>) : <p className="muted">Completed outcomes will summarize here.</p>}</div><div className="insight-block"><h3>Asking for human help</h3>{insights.data?.escalationRequests?.length ? insights.data.escalationRequests.map(item => <p key={item.label}>{item.label}<b>{item.count}</b></p>) : <p className="muted">Anonymous escalation patterns will appear here.</p>}</div></aside>
    </div>
  </main><Dialog open={newOpen} onOpenChange={setNewOpen}><DialogContent><DialogHeader><DialogTitle>Create a Skoot Pack</DialogTitle><DialogDescription>One Pack represents one evolving method. You can update it without asking students to copy a new prompt.</DialogDescription></DialogHeader><div className="creator-new-form"><Label>Pack name<Input value={packForm.name} onChange={event => setPackForm({ ...packForm, name: event.target.value })} placeholder="Launch Skoot Pack" /></Label><Label>What is it for?<Textarea value={packForm.description} onChange={event => setPackForm({ ...packForm, description: event.target.value })} placeholder="Decision rules for validating and launching a new offer." /></Label><Button disabled={!packForm.name.trim() || create.isPending} onClick={() => create.mutate(packForm)}>{create.isPending ? "Creating…" : "Create Pack"}</Button></div></DialogContent></Dialog><Dialog open={guidedOpen} onOpenChange={setGuidedOpen}><DialogContent className="max-h-[92vh] max-w-5xl overflow-y-auto"><DialogHeader><DialogTitle>{selected ? "Build the path your students will follow" : "Start with a short Pack shape"}</DialogTitle><DialogDescription>You can change every word. Nothing reaches students until you approve a version.</DialogDescription></DialogHeader><GuidedPackBuilder packId={selectedId} onPublished={async newPackId => { await refresh(); setSelectedId(newPackId); setGuidedOpen(false); }} /></DialogContent></Dialog></div>;
}
